### PR TITLE
Rename aws variable names in pdf pipeline to include "sandbox"

### PR DESCRIPTION
**Pull request by karenc**
Change `aws-access-key-id` and `aws-secret-access-key` to
`aws-sandbox-secret-key-id` and `aws-sandbox-secret-access-key`
respectively so that we match what is on the aws secrets manager.

The "sandbox" bit refers to "openstax-dev-sandbox".

### CODE REVIEW

**Comment by tomjw64** [comment]
The variables without "sandbox" in the name are going to refer to the non-sandbox organization I assume?

**Comment by karenc** [comment]
@tomjw64 Actually the variables without "sandbox" don't exist, but I just wanted to make it clear these are for sandbox.

**Comment by tomjw64** [comment]
So if this is merged and used on concourse-dev0, then the pipeline will stop working?

**Comment by karenc** [comment]
@tomjw64 No, this PR is required to make the pipeline work on concourse-dev0.

**Review by therealmarv — APPROVED** [review]
looks good from my side.

**Pull request merged**
